//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklads.DataAp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiale
    {
        public int Nomer { get; set; }
        public string name { get; set; }
        public int Edinica_izmerenia { get; set; }
        public int ostatok { get; set; }
        public int sklad { get; set; }
    
        public virtual Edinica_izmerenia Edinica_izmerenia1 { get; set; }
        public virtual Sklad Sklad1 { get; set; }
    }
}
