//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklads.DataAp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test_zadanieEntities1 : DbContext
    {
        public static Test_zadanieEntities1 Context;
        public static Test_zadanieEntities1 GetContext() 
        {
            if (Context==null)
            {
                Context = new Test_zadanieEntities1();
            }
            return Context;
        }
        public Test_zadanieEntities1()
            : base("name=Test_zadanieEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Edinica_izmerenia> Edinica_izmerenia { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_materiala> Type_materiala { get; set; }
        public virtual DbSet<Materiale> Materiale { get; set; }
        public virtual DbSet<Registr> Registr { get; set; }
    }
}
