//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklads.DataAp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registr
    {
        public int Id { get; set; }
        public string Login_user { get; set; }
        public string Pasword_user { get; set; }
    }
}
